site_name: Python IRC Docs

theme: 
  name: "material"

watch:
  - pyrc

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx

nav:
  - Python IRC Docs: index.md
  - How-To Guides: how-to-guides.md
  - References:
    - Client API References: reference/client.md
    - Client Classes Reference: reference/classes.md
  - explanation.md
