on:
    pull_request:
        branches:
            - master
            - develop

jobs:
    format_black:
        name: Black Format Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Check Code
              uses: rickstaa/action-black@v1
              with: 
                black_args: "./pyrc --check"
